### ISSUE TITLE
problem with file extension

### ISSUE THREAD

**Issue by rajputarun** [oguzkaan-mavice/Cooursera_Castpone#1]
Hi fella, we are taking same IBM data science course. I was not able to submit my review on coursera, so I thought to reach out to you here. Your notebook name is "First_Assigment", but it is missing file extension because of which github is not able to render is. So just make it "First_Assigment.ipynb". Note the file extension. 
Kudos!

**Comment by oguzkaan-mavice** [comment]
Hi fellas, thank you for your help. I added .ipynb extension.

23 Şub 2020 Paz, saat 20:12 tarihinde Arun <notifications@github.com> şunu
yazdı:
